# Generated by Django 3.1.7 on 2021-04-06 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_mechanics_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanics_details',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
