# Generated by Django 3.1.7 on 2021-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_mechanics_details_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='descriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobilenumber', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
