# Generated by Django 3.1.7 on 2021-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0005_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_name', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_mobile', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150, null=True)),
                ('payment_status', models.CharField(max_length=150, null=True)),
                ('otp', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
