# Generated by Django 3.1.7 on 2021-04-01 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0007_admin_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanics_details',
            old_name='address',
            new_name='email',
        ),
        migrations.AddField(
            model_name='mechanics_details',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
