# Generated by Django 3.1.7 on 2021-04-02 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0008_auto_20210402_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanics_details',
            name='mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
