# Generated by Django 3.1.7 on 2021-04-14 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0011_descriptions_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='des_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
