# Generated by Django 3.1.7 on 2021-04-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0013_auto_20210415_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='des_id',
            new_name='username',
        ),
    ]
