# Generated by Django 3.1.7 on 2021-04-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0015_remove_descriptions_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='username',
        ),
    ]
