# Generated by Django 3.1.7 on 2021-04-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0019_remove_status_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_table',
        ),
    ]
